version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_chatbot
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - informes_compartidos:/app/static/informes  # <--- NUEVO
    depends_on:
      - db
      - nlp
    env_file:
      - ./backend/.env
    restart: always

  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    container_name: nlp_service
    ports:
      - "8001:8001"
    volumes:
      - ./nlp:/app
      - huggingface_cache:/root/.cache/huggingface
      - spacy_cache:/root/.cache/spacy
      - informes_compartidos:/app/static/informes
    env_file:
      - ./nlp/.env
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_gradio
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
      - nlp
    restart: always

  db:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongodb_data:
  huggingface_cache:
  spacy_cache:
  informes_compartidos: